### PR TITLE
feat(websocket): add websocket connection docs

### PR DESCRIPTION
**Pull request by sunlee-newyork**
Add instructions on how to subscribe to RPC websocket (thank you @jacobcreech !)

### CODE REVIEW

**Comment by sunlee-newyork** [comment]
@jacobcreech i'm @foodeatyum.sol on discord btw

**Review by jacobcreech — COMMENTED** [review]
@sunlee-newyork This may be a great addition to the `Local Development` page after `Setting up Connections`.

https://solanacookbook.com/recipes/local-development.html#setting-up-connections

I don't know how much it may warrant an entirely new page as we do not plan on adding examples for all RPC methods at this time.

Also, for the preview, what do you think of having even less, such as:

```
const connection = new Connection( clusterApiUrl( 'devnet' ), 'confirmed' );

connection.onAccountChange(
    wallet.publicKey(),
    ( updatedAccountInfo, context ) => console.log( 'Updated account info: ', updatedAccountInfo ),
    'confirmed',
  );
```

**Comment by sunlee-newyork** [comment]
@jacobcreech sounds great! i'll make those changes and push up

**Comment by sunlee-newyork** [comment]
@jacobcreech i left `const wallet = Keypair.generate()` because it might confuse some people where `wallet` variable came from

**Review by jacobcreech — APPROVED** [review]
Awesome! Thanks for the contribution

**Comment by sunlee-newyork** [comment]
@jacobcreech thanks for the insight to begin with, happy to contribute back!

**Pull request merged**
